name: zippy
description: "Zippy"
publish_to: 'none' 

version: 1.0.0+3

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  supabase_flutter: ^2.5.0
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  image_picker: ^1.0.8
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  flutter_inappwebview: ^6.0.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  google_mobile_ads: ^5.0.0
  flutter_slidable: ^3.1.0
  share_plus: ^9.0.0
  app_tracking_transparency: ^2.0.4
  flutter_naver_login: ^1.8.0
  random_avatar: ^0.0.8
  kakao_flutter_sdk_talk: ^1.9.1+2 
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  in_app_review: ^2.0.9
  lottie: ^3.1.0
  flutter_expandable_fab: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  test: any
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/app/icon.png"
  windows:
    generate: true
    image_path: "assets/app/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app/icon.png"

flutter:

  uses-material-design: true

  assets:
    - .env
    - .env.development
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/app/
    - assets/animation/
    
  fonts:
    - family: PretendardVariable
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
