name: cocomu
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  supabase_flutter: ^2.5.0
  flutter_dotenv: ^5.1.0
  get_storage: ^2.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.19.0
  image_picker: ^1.0.8
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  html: ^0.15.4
  webview_flutter: ^4.7.0
  beautiful_soup_dart: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  test: any
  build_runner: ^2.4.9
  freezed: ^2.5.1
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - .env
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
