name: zippy
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  supabase_flutter: ^2.5.0
  flutter_dotenv: ^5.1.0
  get_storage: ^2.1.1
  intl: ^0.19.0
  image_picker: ^1.0.8
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  flutter_inappwebview: ^6.0.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  google_mobile_ads: ^5.0.0
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  test: any

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/fonts/
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: PretendardVariable
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
